application.data-dir: ${DATA_DIR:images-store}
server.port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/inventory #Secara default localhost, ketika menjalankan docker maka yang terpanggil adalah DB_HOST
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  messages.basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
springdoc:
  swagger-ui:
    path: /swagger-ui.html
